---
- name: restart app
  become: true
  systemd:
    name: "{{ alert_service }}"
    state: restarted
    daemon_reload: true

- name: systemd daemon reload
  become: true
  systemd:
    daemon_reload: true