---
- name: restart app
  become: true
  systemd:
    name: "{{ app_user }}"
    state: restarted
    daemon_reload: true

- name: systemd daemon reload
  become: true
  systemd:
    daemon_reload: true

- name: reload web
  become: true
  service:
    name: caddy
    state: reloaded