---
- name: Disable root login
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: Output directory for Diffie-Hellman parameters exists
  file:
    path: "{{ dhparam_file | dirname }}"
    state: directory

- name: Generate dhparam file for web
  command: "openssl dhparam -out {{ dhparam_file }} 4096"

