---
- name: Install needed packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - sqlite3
    - git
    - autoconf
    - gcc
    - make
    - libssl-dev
    - libncurses-dev
    - g++

- name: Download asdf manager
  get_url:
    url: https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz
    dest: /tmp/asdf.tar.gz

- name: Create asdf path
  file:
    path: "~/.asdf"
    state: directory
    mode: 0755
    owner: k00d
    group: k00d

- name: Extract asdf manager
  unarchive:
    remote_src: true
    src: /tmp/asdf.tar.gz
    dest: ~/.asdf/
    mode: 0755
    owner: k00d
    group: k00d

- name: Create bash_profile
  file:
    path: "~/.bash_profile"
    state: touch

- name: Add asdf to PATH in bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH="$HOME/.asdf/:$PATH"'
    state: present

- name: Add asdf to PATH in bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH="$HOME/.asdf/shims:$PATH"'
    state: present

- name: Create tool-versions
  file:
    path: "~/.tool-versions"
    state: touch

- name: Add Erlang version to tool-versions
  lineinfile:
    path: ~/.tool-versions
    line: 'erlang 27.3.4.1'
    state: present

- name: Add Elixir version to tool-versions
  lineinfile:
    path: ~/.tool-versions
    line: 'elixir 1.18.4-otp-27'
    state: present

- name: Add asdf Erlang plugin
  command: "~/.asdf/asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git"
  args:
    creates: "~/.asdf/plugins/erlang"

- name: Add asdf Elixir plugin
  command: "~/.asdf/asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git"
  args:
    creates: "~/.asdf/plugins/elixir"

- name: Install Erlang
  command: "~/.asdf/asdf install erlang 27.3.4.1"
  args:
    creates: "~/.asdf/installs/erlang/27.3.4.1"

- name: Install Elixir
  command: "~/.asdf/asdf install elixir 1.18.4-otp-27"
  args:
    creates: "~/.asdf/installs/elixir/1.18.4-otp-27"
