---
- name: Install needed packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - sqlite3
    - git
    - autoconf
    - gcc
    - make
    - libssl-dev
    - libncurses-dev
    - g++

- name: Download asdf manager
  get_url:
    url: https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz
    dest: /tmp/asdf.tar.gz

- name: Create asdf path
  become: true
  file:
    path: "/opt/asdf"
    state: directory
    mode: 0755
    owner: k00d
    group: k00d

- name: Extract asdf manager
  become: true
  unarchive:
    remote_src: true
    src: /tmp/asdf.tar.gz
    dest: /opt/asdf/
    mode: 0755
    owner: k00d
    group: k00d

- name: Create bash_profile
  file:
    path: "~/.bash_profile"
    state: touch

- name: Add asdf to PATH
  lineinfile:
    path: ~/.bash_profile
    line: 'export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"'
    state: present
  notify: restart shell

- name: Create tool-versions
  file:
    path: "~/.tool-versions"
    state: touch

- name: Add asdf to PATH
  lineinfile:
    path: ~/.tool-versions
    line: 'erlang 27.3.4.1'
    state: present
  with_items:
    - erlang 27.3.4.1
    - elixir 1.18.4-otp-27

- name: Add asdf Erlang plugin
  command: asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git

- name: Add asdf Elixir plugin
  command: asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git

- name: Install Erlang
  command: asdf install erlang 27.3.4.1

- name: Install Elixir
  command: asdf install elixir 1.18.4-otp-27
