---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo privileges and doesnt require passwords
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Create default user
  user:
    name: "{{ username }}"
    groups: sudo
    password: "{{ password }}"
    shell: /bin/bash
    update_password: always
    state: present

- name: Add public key for default user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ public_key }}"
