---
- name: Check if needed variables are defined
  assert:
    that:
      - app_git_repo is defined
      - app_git_path is defined
    fail_msg: " 'item' is not defined or empty"

- name: Ensure ssh key is present
  become: true
  copy:
    src: /root/.ssh/{{ item }}
    dest: /home/k00d/.ssh/{{ item }}
    owner: k00d
    group: k00d
    mode: 0600
    remote_src: yes
  with_items:
    - "id_ed25519_k00d.pub"
    - "id_ed25519_k00d"

- name: Create application git path
  become: true
  file:
    path: "{{ app_git_path }}"
    state: directory
    mode: 0755
    owner: "k00d"
    group: "k00d"

- name: Pull the latest changes from the git repository
  git:
    repo: "{{ app_git_repo }}"
    dest: "{{ app_git_path }}"
    ssh_opts: "-i ~/.ssh/id_ed25519_k00d"
    version: "main"
    force: true

- name: Ensure setup is completed
  command: "make setup"
  args:
    chdir: "{{ app_git_path }}"

- name: Make the release
  command: "make release"
  args:
    chdir: "{{ app_git_path }}"