---
- name: Check if needed variables are defined
  assert:
    that:
      - app_git_repo is defined
      - app_git_path is defined
      - app_path is defined
      - app_user is defined
      - app_group is defined
      - app_name is defined
      - app_version is defined
    fail_msg: " 'item' is not defined or empty"

- name: Pull the latest changes from the git repository
  git:
    repo: "{{ app_git_repo }}"
    dest: "{{ app_git_path }}"
    ssh_opts: "-i ~/.ssh/id_ed25519_k00d"
    version: "main"
    force: true

- name: Clean the release
  shell: make clean
  args:
    chdir: "{{ app_git_path }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.asdf/shims:{ ansible_env.HOME }}/.asdf/:{{ ansible_env.PATH }}"

- name: Make the release
  command: make release
  args:
    chdir: "{{ app_git_path }}"

- name: Extract application release
  become: true
  unarchive:
    remote_src: true
    src: "{{ app_git_path }}/release/{{ app_name }}-{{ app_version }}.tar.gz"
    dest: "{{ app_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Set application user as owner for extracted files
  become: true
  file:
    dest: "{{ app_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: true

- name: Stop application service
  become: true
  service:
    name: "{{ app_name }}"
    enabled: true
    state: stopped

- name: Start application service
  become: true
  service:
    name: "{{ app_name }}"
    enabled: true
    state: started
