---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes

- name: Clean nginx config directory
  file:
    path: /etc/nginx
    state: absent

- name: H5bp nginx configuration
  git:
    repo: https://github.com/h5bp/server-configs-nginx.git
    dest: /etc/nginx
    force: yes
    version: main
  notify: restart nginx

- name: Output directory for Diffie-Hellman parameters exists
  file:
    path: "{{ dhparam_file | dirname }}"
    state: directory

- name: Generate dhparam file for nginx
  command: "openssl dhparam -out {{ dhparam_file }} 4096"