---
- name: Install needed packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - lsb-release
    - software-properties-common

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-compose

- name: Start systemd service
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull needed docker containers
  docker_image:
    name: "{{ item.image }}"
    source: pull
  with_items: "{{ docker_containers }}"
  when: docker_containers | length > 0

- name: Run docker container with restart policies
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    restart_policy: "{{ item.restart_policy }}"
    ports:
      - "{{ item.ports }}"
    volumes:
      - "{{ item.volumes }}"
  with_items: "{{ docker_containers }}"
  when: docker_containers | length > 0
