---
- hosts: unet
  user: root
  become: true
  vars:
    username: k00d
    password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') | password_hash('sha512') }}"
    public_key: "{{ lookup('file', '~/.ssh/id_ed25519_kood.pub') }}"
  roles: 
   - common
   - ufw
   - user
   - ssh
   - nginx
   #- docker
